/**
 * A 400 × 400 PNG in one colour — the image sample with which the crop dialog
 * is checked. Big enough that the frame has an area to drag and the 96 px
 * minimum side (`crop-geometry.ts`) leaves room to shrink it.
 *
 * **One file instead of two copies** (a review finding, 2026-08-12): since the
 * axe run checks the dialog as well, two suites need it. An image sample that
 * stands at two places is one that at some point has a different size at one of
 * them — and then the one case measures something other than the other.
 */
export const CROP_SAMPLE_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAEhUlEQVR42u3VMQEA' +
  'AAjDMJTMvxRcgQZucsRAn1YnAwBXJQIABgKAgQBgIAAYCAAYCAAGAoCBAGAgABgI' +
  'ABgIAAYCgIEAYCAAGAgAGAgABgKAgQBgIAAYCAAYCAAGAoCBAGAgABgIABgIAAYC' +
  'gIEAYCAAGAgAGAgABgKAgQBgIAAYCAAYCAAGAoCBAGAgAGAgABgIAAYCgIEAYCAA' +
  'YCAAGAgABgKAgQBgIABgIAAYCAAGAoCBAGAgAGAgABgIAAYCgIEAYCAAYCAAGAgA' +
  'BgKAgQBgIABgIAAYCAAGAoCBAGAgAGAgABgIAAYCgIEAYCAiAGAgABgIAAYCgIEA' +
  'gIEAYCAAGAgABgKAgQCAgQBgIAAYCAAGAoCBAICBAGAgABgIAAYCgIEAgIEAYCAA' +
  'GAgABgKAgQCAgQBgIAAYCAAGAoCBAICBAGAgABgIAAYCgIEAgIEAYCAAGAgABgIA' +
  'BgKAgQBgIAAYCAAGAgAGAoCBAGAgABgIAAYCAAYCgIEAYCAAGAgABgIABgKAgQBg' +
  'IAAYCAAGAgAGAoCBAGAgABgIAAYCAAYCgIEAYCAAGAgABgIABgKAgQBgIAAYCAAG' +
  'IgIABgKAgQBgIAAYCAAYCAAGAoCBAGAgABgIABgIAAYCgIEAYCAAGAgAGAgABgKA' +
  'gQBgIAAYCAAYCAAGAoCBAGAgABgIABgIAAYCgIEAYCAAGAgAGAgABgKAgQBgIAAY' +
  'CAAYCAAGAoCBAGAgAGAgABgIAAYCgIEAYCAAYCAAGAgABgKAgQBgIABgIAAYCAAG' +
  'AoCBAGAgAGAgABgIAAYCgIEAYCAAYCAAGAgABgKAgQBgIABgIAAYCAAGAoCBAGAg' +
  'AGAgABgIAAYCgIEAYCBCAGAgABgIAAYCgIEAgIEAYCAAGAgABgKAgQCAgQBgIAAY' +
  'CAAGAoCBAICBAGAgABgIAAYCgIEAgIEAYCAAGAgABgKAgQCAgQBgIAAYCAAGAoCB' +
  'AICBAGAgABgIAAYCgIEAgIEAYCAAGAgABgKAgYgAgIEAYCAAGAgABgIABgKAgQBg' +
  'IAAYCAAGAgAGAoCBAGAgABgIAAYCAAYCgIEAYCAAGAgABgIABgKAgQBgIAAYCAAG' +
  'AgAGAoCBAGAgABgIAAYCAAYCgIEAYCAAGAgABgIABgKAgQBgIAAYCAAYCAAGAoCB' +
  'AGAgABgIABgIAAYCgIEAYCAAGAgAGAgABgKAgQBgIAAYCAAYCAAGAoCBAGAgABgI' +
  'ABgIAAYCgIEAYCAAGAgAGAgABgKAgQBgIAAYCAAYCAAGAoCBAGAgABiICAAYCAAG' +
  'AoCBAGAgAGAgABgIAAYCgIEAYCAAYCAAGAgABgKAgQBgIABgIAAYCAAGAoCBAGAg' +
  'AGAgABgIAAYCgIEAYCAAYCAAGAgABgKAgQBgIABgIAAYCAAGAoCBAGAgAGAgABgI' +
  'AAYCgIEAgIEAYCAAGAgABgKAgQCAgQBgIAAYCAAGAoCBAICBAGAgABgIAAYCgIEA' +
  'gIEAYCAAGAgABgKAgQCAgQBgIAAYCAAGAoCBAICBAGAgABgIAAYCwFcL+5qcqNVJ' +
  'mbsAAAAASUVORK5CYII=';
