export {
  AI_MODEL_CHOICES,
  DEFAULT_AI_MODEL,
  type AiModelChoice,
} from './ai-models.ts';
export {
  DEFAULT_AI_TIMEOUT_MS,
  MOVED_AI_ENV_VARS,
  aiAvailable,
  aiAvailableForTenant,
  describeAiConfigGap,
  movedAiEnvVarsStillSet,
  movedAiEnvWarning,
  resolveAiConfig,
  type AiSettingsFields,
  type ResolvedAiConfig,
} from './ai-config.ts';
export {
  AI_PRECONDITIONS,
  AI_REGION_DEFAULT,
  aiApiKeyWriteSchema,
  aiRegionSchema,
  parseTenantAiSwitch,
  systemAiSettingsResponseSchema,
  systemAiSettingsSchema,
  tenantAiSwitchSchema,
  updateSystemAiSettingsRequestSchema,
  updateTenantAiSwitchRequestSchema,
  type AiRegion,
  type SystemAiSettings,
  type SystemAiSettingsResponse,
  type TenantAiSwitch,
  type UpdateSystemAiSettingsRequest,
  type UpdateTenantAiSwitchRequest,
} from './ai-settings.ts';
export {
  AI_DRAFT_CONDITION_TARGET,
  AI_DRAFT_INVALID_LEAD,
  AI_DRAFT_QUESTION_VARIANTS,
  adoptAiFormDraft,
  aiDraftAcceptsQuestionType,
  aiFormDraftSchema,
  type AiFormDraftAdoption,
  type AiFormDraftRefusal,
} from './ai-form-draft.ts';
export {
  AI_FAILURE_KINDS,
  AI_PROMPT_MAX,
  AI_QUOTA_EXHAUSTED_MESSAGE,
  aiFailureKindSchema,
  aiFormDraftResponseSchema,
  aiFormPromptRequestSchema,
  aiProviderSchema,
  aiUsageSampleSchema,
  buildAiFormRequest,
  formLanguageSchema,
  parseAiFormDraftResponse,
  parseAiQuota,
  type AiFailureKind,
  type AiFormDraftResponse,
  type AiFormOutcome,
  type AiFormPromptRequest,
  type AiFormRequest,
  type AiProvider,
  type AiUsageSample,
  type FormLanguage,
} from './ai.ts';
export {
  AI_MONTHLY_CALL_LIMIT_MAX,
  AI_PROMPT_RETENTION_DAYS,
  AI_USAGE_PERSON_RETENTION_DAYS,
  DEFAULT_AI_MONTHLY_CALL_LIMIT,
  aiQuotaRemaining,
  aiQuotaSchema,
  aiQuotaWriteSchema,
  parseAiQuotaWrite,
  type AiQuota,
  type AiQuotaWrite,
} from './ai-usage.ts';
export {
  DEFAULT_OIDC_BUTTON_LABEL,
  ACCOUNT_INVITATION_TTL_DAYS,
  OIDC_OUTCOME_PARAM,
  PASSWORD_RESET_INVALID_MESSAGE,
  PASSWORD_RESET_RETENTION_DAYS,
  PASSWORD_RESET_TTL_MINUTES,
  emailAddressSchema,
  emailChangeSchema,
  groupSummarySchema,
  loginRequestSchema,
  personNameSchema,
  loginResponseSchema,
  membershipSummarySchema,
  oidcOutcomeSchema,
  oidcProviderSchema,
  oidcProvidersSchema,
  parseLoginRequest,
  parseLoginResponse,
  parseOidcProviders,
  parseSessionRevocation,
  parseSessionUser,
  passwordChangeSchema,
  passwordResetConfirmSchema,
  passwordResetRequestSchema,
  permissionsSchema,
  profileUpdateSchema,
  sessionRevocationSchema,
  sessionUserSchema,
  switchTenantRequestSchema,
  tenantSummarySchema,
  type EmailChange,
  type GroupSummary,
  type LoginRequest,
  type LoginResponse,
  type MembershipSummary,
  type OidcOutcome,
  type OidcProvider,
  type PasswordChange,
  type PasswordResetConfirm,
  type PasswordResetRequest,
  type Permissions,
  type ProfileUpdate,
  type SessionRevocation,
  type SessionUser,
  type SwitchTenantRequest,
  type TenantSummary,
} from './auth.ts';
export {
  DEFAULT_TENANT_BRANDING,
  STRIPE_COLOR_MAX,
  TENANT_LOGO_REFS,
  deliverableBranding,
  hexColorSchema,
  isBrandColor,
  isTenantLogoRef,
  parseTenantBrandingSettings,
  tenantBrandingSchema,
  tenantBrandingSettingsSchema,
  tenantBrandingWriteSchema,
  tenantLogoRefSchema,
  tenantLogoSchema,
  uploadedLogoRef,
  type DeliverableBranding,
  type DeliverableLogo,
  type StoredTenantBranding,
  type TenantBranding,
  type TenantBrandingSettings,
  type TenantBrandingWrite,
  type TenantLogoRef,
} from './branding.ts';
export {
  apiEnvSchema,
  nodeEnvSchema,
  parseApiEnv,
  type ApiEnv,
  type NodeEnv,
} from './env.ts';
export {
  ATTACHMENT_HINT,
  MAX_ATTACHMENT_BYTES,
  MAX_FILES_PER_RESPONSE,
  MAX_RESPONSE_BYTES,
  MAX_TENANT_LOGO_BYTES,
  TENANT_LOGO_HINT,
  MAX_UPLOAD_BYTES,
  UNCLAIMED_BYTES_PER_ADDRESS_FORM,
  UNCLAIMED_FILES_PER_ADDRESS_FORM,
  UNCLAIMED_FILE_LIFETIME_MS,
  UPLOAD_BYTES_PER_ADDRESS_HOUR,
  UPLOAD_FILES_PER_ADDRESS_HOUR,
  UPLOAD_WINDOW_MS,
} from './file-limits.ts';
export {
  ATTACHMENT_ACCEPT,
  ATTACHMENT_CONTENT_TYPES,
  FILE_REF_BYTES,
  FILE_SIGNATURE_BYTES,
  TENANT_LOGO_CONTENT_TYPES,
  UPLOAD_CONTENT_TYPES,
  contentTypeLabels,
  deliverableContentType,
  detectContentType,
  fileNameSchema,
  fileRefSchema,
  isAllowedContentType,
  isFileRef,
  type FileRef,
  type UploadContentType,
} from './file-types.ts';
export { baseUrlSchema, normaliseBaseUrl } from './base-url.ts';
export {
  effectiveReplyTo,
  effectiveReplyToSchema,
  isUnusableReplyTo,
  replyToAddressSchema,
  replyToLevelSchema,
  replyToOriginSchema,
  type EffectiveReplyTo,
  type ReplyToLevel,
  type ReplyToOrigin,
} from './reply-to.ts';
export {
  describeMailConfigError,
  parseStoredSmtpBlock,
  smtpAuthSchema,
  smtpBlockSchema,
  type SmtpAuth,
  type SmtpBlock,
} from './mail-config.ts';
export {
  aiModelUsageSchema,
  aiStatusSchema,
  exceeds,
  jobKindSchema,
  jobOutcomeSchema,
  jobStatusSchema,
  MAIL_FAILURE_WINDOW_MS,
  mailQueueStatusSchema,
  OPS_THRESHOLDS,
  opsStatusSchema,
  parseOpsStatus,
  storageStatusSchema,
  ACK_DURATION_LABELS,
  ACK_DURATION_MS,
  ACK_NOTE_MAX,
  OPS_METRIC_SUBJECTS,
  ackDurationSchema,
  acknowledgeAlertRequestSchema,
  acknowledgementHolds,
  alertAcknowledgementSchema,
  opsAlertStateSchema,
  opsMetricSchema,
  type AckDuration,
  type AcknowledgeAlertRequest,
  type AiModelUsage,
  type AiStatus,
  type AlertAcknowledgement,
  type JobStatus,
  type MailQueueStatus,
  type OpsAlertState,
  type OpsJobKind,
  type OpsJobOutcome,
  type OpsMetricName,
  type OpsSeverity,
  type OpsStatus,
  type StorageStatus,
} from './ops-status.ts';
export {
  healthResponseSchema,
  healthStatusSchema,
  parseHealthResponse,
  parseReadinessResponse,
  readinessResponseSchema,
  type HealthResponse,
  type HealthStatus,
  type ReadinessResponse,
} from './health.ts';
export {
  // `evaluateCondition` is deliberately absent: it answers a non-applicable
  // operator/type pair with `false` where `visibleQuestionIds` shows the
  // question, and the more obvious name was the wrong door. See its comment in
  // `condition.ts`.
  conditionDefectSchema,
  findUnresolvableConditions,
  unresolvableConditionMessage,
  unresolvableConditionText,
  visibleQuestionIds,
  UNRESOLVABLE_CONDITION_LEAD,
  type ConditionDefect,
  type UnresolvableCondition,
} from './condition.ts';
export {
  copyrightNotice,
  copyrightYears,
  parseMitCopyright,
  type MitCopyright,
} from './copyright.ts';
export {
  allQuestions,
  answerableQuestions,
  canBeConditionSource,
  conditionOperatorSchema,
  conditionOperatorsFor,
  questionConditionSchema,
  formDefinitionSchema,
  isAnswerableQuestion,
  isChoiceQuestion,
  otherLabelOf,
  otherPositionOf,
  otherPositionSchema,
  pageSchema,
  parseFormDefinition,
  questionOptionSchema,
  questionSchema,
  questionTypeSchema,
  questionWidthSchema,
  eventEntrySchema,
  tableCellTypeSchema,
  tableRowLimit,
  EVENT_CAPACITY_MAX,
  TABLE_COLUMNS_MAX,
  TABLE_ROWS_MAX,
  type AnswerableQuestion,
  type ChoiceQuestion,
  type ConditionOperator,
  type QuestionCondition,
  type EventEntry,
  type EventQuestion,
  type FormDefinition,
  type FormPage,
  type OtherPosition,
  type Question,
  type QuestionOption,
  type QuestionType,
  type QuestionWidth,
  type TableCellType,
  type TableColumn,
  type TableQuestion,
} from './form-schema.ts';
export { tableCanGrow } from './table-growth.ts';
export {
  detachFormDefinition,
  detachQuestions,
  duplicateFormDefinition,
  duplicateQuestion,
  duplicateQuestions,
  type FormDuplication,
  type QuestionDuplication,
} from './question-duplicate.ts';
export {
  sampleAnswers,
  type SampleAnswers,
  type UnfillableQuestion,
} from './sample-answers.ts';
export {
  FORM_TEMPLATE_NAME_MAX,
  formTemplateContentSchema,
  formTemplateFormContentSchema,
  formTemplateInstanceSchema,
  formTemplateKindSchema,
  formTemplateListSchema,
  formTemplatePageContentSchema,
  formTemplateQuestionContentSchema,
  formTemplateSummarySchema,
  parseFormTemplateInstance,
  parseFormTemplateList,
  parseFormTemplateSummary,
  renameFormTemplateRequestSchema,
  saveFormTemplateRequestSchema,
  templateQuestionCount,
  updateFormTemplateContentRequestSchema,
  type FormTemplateContent,
  type FormTemplateInstance,
  type FormTemplateKind,
  type FormTemplateList,
  type FormTemplatePageInstance,
  type FormTemplateQuestionInstance,
  type FormTemplateSummary,
  type RenameFormTemplateRequest,
  type SaveFormTemplateRequest,
  type UpdateFormTemplateContentRequest,
} from './form-templates.ts';
export {
  DEFAULT_ADDRESS_COUNTRY,
  EVENT_SEATS_MAX,
  MATRIX_UNKNOWN_ROW_CODE,
  TABLE_ROW_LIMIT_CODE,
  answerSchemaFor,
  answerValueSchema,
  attachmentsOf,
  buildAnswersSchema,
  canonicalAnswerValue,
  isAddressAnswer,
  isBlankAnswer,
  isEventAnswer,
  isFileAnswer,
  isMatrixAnswer,
  isTableAnswer,
  parseAnswers,
  safeParseAnswers,
  safeParseDraftAnswers,
  seatsOf,
  structuredAnswerShape,
  type AddressAnswer,
  type AnswerMap,
  type AnswerValue,
  type ChoiceAnswer,
  type EventAnswer,
  type FileAnswer,
  type FileAttachment,
  type MatrixAnswer,
  type ShapedAnswer,
  type StructuredAnswer,
  type TableAnswer,
  type TableCellValue,
  type AnswersSchemaOptions,
} from './response-validation.ts';
export {
  FORM_PAGE_SIZE_DEFAULT,
  FORM_PAGE_SIZE_MAX,
  FORM_SEARCH_MAX_LENGTH,
  ORPHANED_PLACEHOLDER_LEAD,
  PLACEHOLDER_PLACE_LABELS,
  createFormRequestSchema,
  formDetailSchema,
  formListQuerySchema,
  formListPageSchema,
  formTitleSchema,
  formPublishDiffSchema,
  formStatusSchema,
  formSummarySchema,
  formVersionSnapshotSchema,
  parseFormDetail,
  parseFormListPage,
  parsePublishPreview,
  parseResponseColumnSet,
  placeholderPlaceSchema,
  publishBlockedConditionSchema,
  publishBlockedPlaceholderSchema,
  publishBlockedSchema,
  publishFormRequestSchema,
  publishPreviewSchema,
  responseColumnSchema,
  responseColumnSetSchema,
  responseDetailSchema,
  updateFormRequestSchema,
  type CreateFormRequest,
  type FormDetail,
  type FormListQuery,
  type FormListPage,
  type FormPublishDiff,
  type FormStatus,
  type FormSummary,
  type FormVersionSnapshot,
  type PlaceholderPlace,
  type PublishBlocked,
  type PublishBlockedCondition,
  type PublishBlockedPlaceholder,
  type PublishDiffQuestion,
  type PublishFormRequest,
  type PublishDiffTypeChange,
  type PublishPreview,
  type ResponseColumn,
  type ResponseColumnSet,
  type ResponseDetail,
  type UpdateFormRequest,
} from './forms.ts';
export {
  boundedRequests,
  exhaustedPosition,
  inDefinitionOrder,
  publicEventSeats,
  seatKey,
  seatRequests,
  snapshotEventSeats,
  withLiveCapacity,
  type SeatPosition,
  type SeatRequest,
} from './event-seats.ts';
export { eventChips, type EventChip } from './event-chips.ts';
export {
  ADDRESS_PARTS,
  COLUMN_KEY_SEPARATOR,
  COLUMN_LABEL_SEPARATOR,
  formatAnswerCell,
  questionColumns,
  type CellGuard,
  type QuestionColumn,
} from './answer-columns.ts';
export { CSV_BOM, CSV_DELIMITER, buildCsv, escapeCsvCell } from './csv.ts';
// `writeCsv` and `buildExportSheet` stay inside the package on purpose: the way
// out of here is `writeExport` below, and a surface that also offered the two
// halves separately would be an invitation to assemble a third one.
export {
  SUBMITTED_AT_COLUMN,
  SUBMITTED_AT_LABEL,
  chooseColumns,
  formatTimestamp,
  pickDefaultColumns,
  renderRow,
  renderSchemalessRow,
  rowMatchesSearch,
  type ColumnSurface,
  type CsvColumn,
  type CsvRow,
  type ExportCell,
  type ExportSheet,
} from './export-sheet.ts';
// **Names here, writers there** — and the separation is measured, not
// stylistic: `export-formats.ts` pulls in `writeXlsx` and with it a 930 kB
// lump of `exceljs` into every bundle that touches it. The export menu of the
// responses view needs the list and the captions — and nothing else; it
// therefore reads `export-format.ts`, which knows no writer.
export {
  EXPORT_FORMAT_LABELS,
  exportFormatSchema,
  type ExportFormat,
} from './export-format.ts';
export {
  EXPORT_FORMATS,
  writeExport,
  type ExportBody,
  type ExportFormatSpec,
} from './export-formats.ts';
export {
  RETIRED_COLUMN_NOTE,
  canonicalJson,
  csvColumns,
  hasUnpublishedChanges,
  publishDiff,
  questionHistory,
  responseColumnGroups,
  responseColumns,
  sameDefinition,
  type HistoricColumn,
  type HistoricQuestion,
  type ResponseColumnGroup,
} from './form-history.ts';
export {
  accessGrantSchema,
  accessProofSchema,
  accessRequestSchema,
  confirmationOf,
  draftAttachmentSchema,
  lockedPublicFormSchema,
  parseAccessGrant,
  parsePublicFormResponse,
  parseResponseDraft,
  parseResponseEdit,
  parseSavedDraft,
  parseSubmitResponse,
  publicAvailabilitySchema,
  publicDisplaySchema,
  publicEventSeatsSchema,
  publicFormResponseSchema,
  publicFormSchema,
  publicRedirectSchema,
  publicTenantSchema,
  readSubmissionRefusal,
  responseDraftSchema,
  responseEditSchema,
  saveDraftRequestSchema,
  savedDraftSchema,
  draftTokenSchema,
  submissionRefusalPositionSchema,
  parseUploadedFile,
  startTokenSchema,
  submissionRefusalReasonSchema,
  submissionRefusalSchema,
  submitResponseRequestSchema,
  submitResponseResponseSchema,
  uploadedFileSchema,
  type AccessGrant,
  type AccessRequest,
  type DraftAttachment,
  type LockedPublicForm,
  type PublicDisplay,
  type PublicEventSeats,
  type PublicForm,
  type PublicFormResponse,
  type PublicTenant,
  type ResponseDraft,
  type ResponseEdit,
  type SaveDraftRequest,
  type SavedDraft,
  type SubmissionRefusal,
  type SubmissionRefusalPosition,
  type SubmissionRefusalReason,
  type SubmitResponseRequest,
  type SubmitResponseResponse,
  type UploadedFile,
} from './public-form.ts';
export {
  ACCOUNT_INVITATION_SEGMENT,
  PASSWORD_RESET_SEGMENT,
  PUBLIC_FORM_SEGMENT,
  RESPONSE_DRAFT_SEGMENT,
  RESPONSE_EDIT_SEGMENT,
  accountInvitationPath,
  passwordResetPath,
  publicFormPath,
  responseDraftPath,
  responseEditPath,
} from './public-urls.ts';
export {
  MAX_DRAFTS_PER_FORM,
  draftDeadline,
  draftExpiresAt,
} from './draft-retention.ts';
export {
  MAX_VALIDATION_ISSUES,
  readValidationProblem,
  toFieldIssues,
  toValidationIssues,
  validationIssueSchema,
  validationProblem,
  validationProblemSchema,
  type ValidationIssue,
  type ValidationProblem,
} from './problem.ts';
export {
  FULL_WIDTH,
  HALF_WIDTH,
  rowPartnerIndex,
  rowsOf,
  withPairedPageWidths,
  withPairedWidths,
  withReleasedRow,
} from './question-rows.ts';
export {
  AVAILABILITY_KEYS,
  EMPTY_SETTINGS_OVERRIDE,
  MAIL_BUDGET_LIMIT_MAX,
  MAIL_BUDGET_WINDOW_MIN_MAX,
  PASSWORD_MAX,
  PASSWORD_MIN,
  REDACTED_PASSWORD,
  REDIRECT_DELAY_MAX,
  SETTINGS_SECTIONS,
  SETTINGS_SECTION_KEYS,
  SYSTEM_FORM_SETTINGS,
  TENANT_SETTINGS_FLOOR,
  completeFormSettingsSchema,
  completeTenantSettingsSchema,
  definedOnly,
  effectiveRedirect,
  effectiveSettings,
  externalUrlSchema,
  fillTenantSettings,
  formSettingsOverrideSchema,
  formSettingsOverrideShape,
  formSettingsPatchSchema,
  formSettingsSchema,
  formSettingsWriteSchema,
  mergeSettings,
  omitAvailabilityKeys,
  parseFormSettings,
  parseFormSettingsOverride,
  parseTenantFormDefaults,
  pruneToOverridden,
  revokesEditLinks,
  safeExternalUrl,
  setSectionOverride,
  settingsOverriddenSchema,
  settingsSectionSchema,
  tenantFormDefaultsSchema,
  tenantSettingsWriteSchema,
  tenantSettingsPatchSchema,
  type AccessWordState,
  type AvailabilityKey,
  type FormSettings,
  type FormSettingsOverride,
  type PartialFormSettings,
  type PartialTenantFormSettings,
  type RedirectTarget,
  type SettingsOverridden,
  type SettingsSection,
  type TenantFormSettings,
} from './form-settings.ts';
export {
  systemMailSettingsSchema,
  systemSmtpAuthWriteSchema,
  systemSmtpDisplaySchema,
  systemSmtpWriteSchema,
  updateSystemMailSettingsRequestSchema,
  type SystemMailSettings,
  type SystemSmtpAuthWrite,
  type SystemSmtpDisplay,
  type SystemSmtpWrite,
  type UpdateSystemMailSettingsRequest,
} from './system-settings.ts';
export {
  parseSetupState,
  setupRequestSchema,
  setupStateSchema,
  type SetupRequest,
  type SetupState,
} from './setup.ts';
/*
  The second superadministrator (ADR-0029) — immediately behind the setup,
  because it asks the same question one installation later: who carries the
  system administration?
*/
export {
  parseSuperadminList,
  superadminListSchema,
  superadminAddedSchema,
  superadminPromoteSchema,
  superadminSchema,
  type Superadmin,
  type SuperadminAdded,
  type SuperadminList,
  type SuperadminPromote,
} from './superadmins.ts';
export {
  ADMIN_GROUP_RANK,
  DEFAULT_GROUP_RANKS,
  DEFAULT_OIDC_EMAIL_CLAIM,
  DEFAULT_OIDC_EMAIL_VERIFIED_CLAIM,
  DEFAULT_OIDC_SCOPES,
  TENANT_DELETE_CONFIRM_MISMATCH_MESSAGE,
  USER_PASSWORD_MAX,
  USER_PASSWORD_MIN,
  accountKindSchema,
  deletedTenantListSchema,
  deletedTenantSchema,
  formMemberListSchema,
  formMemberSchema,
  formMemberWriteSchema,
  groupDetailSchema,
  groupListSchema,
  groupWriteSchema,
  mailIdentityAuthWriteSchema,
  mailIdentityConfigSchema,
  mailIdentityWriteSchema,
  oidcConfigSchema,
  oidcConfigWriteSchema,
  parseDeletedTenantList,
  parseFormMemberList,
  parseGroupList,
  parseMailIdentityConfig,
  parseOidcConfig,
  parseTenantBaseUrl,
  parseTenantReplyTo,
  parseTenantMemberList,
  parseTenantOverview,
  parseTestMailResult,
  tenantBaseUrlSchema,
  tenantBaseUrlWriteSchema,
  tenantReplyToSchema,
  tenantReplyToWriteSchema,
  tenantCreateSchema,
  tenantFirstAdminSchema,
  tenantInvitedAdminSchema,
  tenantDeleteSchema,
  tenantMemberCreateSchema,
  tenantMemberCreatedSchema,
  tenantMemberListSchema,
  tenantMemberPasswordSchema,
  tenantMemberSchema,
  tenantMemberUpdateSchema,
  tenantOverviewRowSchema,
  tenantOverviewSchema,
  testMailRequestSchema,
  testMailResultSchema,
  type AccountKind,
  type FormMember,
  type FormMemberList,
  type FormMemberWrite,
  type GroupDetail,
  type GroupList,
  type GroupWrite,
  type MailIdentityAuthWrite,
  type MailIdentityConfig,
  type MailIdentityWrite,
  type OidcConfig,
  type OidcConfigWrite,
  type TenantBaseUrl,
  type TenantBaseUrlWrite,
  type TenantReplyTo,
  type TenantReplyToWrite,
  type TenantCreate,
  type TenantMember,
  type TenantMemberCreate,
  type TenantMemberCreated,
  type DeletedTenant,
  type DeletedTenantList,
  type TenantDelete,
  type TenantMemberList,
  type TenantMemberPassword,
  type TenantMemberUpdate,
  type TenantOverview,
  type TenantOverviewRow,
  type TestMailRequest,
  type TestMailResult,
} from './tenant-admin.ts';
export {
  PURGE_STORAGE_UNAVAILABLE_MESSAGE,
  RESPONSE_BULK_DELETE_MAX,
  RESTORE_REFUSAL_MESSAGES,
  TRASH_PURGE_BATCH_SIZE,
  TRASH_RETENTION_DAYS,
  bulkDeleteResponsesRequestSchema,
  deletedFormSchema,
  deletedResponseSchema,
  readRestoreRefusal,
  restoreRefusalReasonSchema,
  restoreRefusalSchema,
  trashCutoff,
  trashPurgeResultSchema,
  trashViewSchema,
  type BulkDeleteResponsesRequest,
  type DeletedForm,
  type DeletedResponse,
  type RestoreRefusal,
  type RestoreRefusalReason,
  type TrashPurgeResult,
  type TrashView,
} from './trash.ts';
export {
  availabilityBadge,
  availabilityOf,
  availabilityStateSchema,
  closingInstant,
  needsResponseCount,
  publicAvailability,
  type AvailabilityBadge,
  type AvailabilityInput,
  type AvailabilityState,
  type FormAvailability,
  type PublicAvailability,
} from './form-availability.ts';
export { SESSION_RETENTION_DAYS } from './session-retention.ts';
export {
  MAIL_BODY_MAX,
  MAIL_LOG_RETENTION_DAYS,
  MAIL_MAX_ATTEMPTS,
  MAIL_RECIPIENT_LIMIT,
  MAIL_SUBJECT_MAX,
  NOTIFICATION_NAME_MAX,
  QUESTION_PLACEHOLDER_PREFIX,
  SYSTEM_PLACEHOLDERS,
  classifyPlaceholder,
  mailFormatSchema,
  mailLogCountsSchema,
  mailLogDetailSchema,
  mailLogEntrySchema,
  mailLogFilterSchema,
  mailLogListResponseSchema,
  mailSenderIdentitySchema,
  mailStatusSchema,
  notificationCreateSchema,
  notificationListResponseSchema,
  notificationQuestionIds,
  notificationRecipientSchema,
  notificationSchema,
  notificationTemplateSchema,
  notificationTriggerInputSchema,
  notificationTriggerSchema,
  notificationTriggersInputSchema,
  notificationUpdateSchema,
  parseMailLogDetail,
  parseMailLogList,
  parseNotificationList,
  placeholderPattern,
  questionPlaceholderIds,
  questionPlaceholderToken,
  recipientQuestionIds,
  rewriteQuestionPlaceholders,
  rewriteRecipientQuestionIds,
  scanPlaceholders,
  systemPlaceholderSchema,
  systemPlaceholderToken,
  type MailFormat,
  type MailLogCounts,
  type MailLogDetail,
  type MailLogEntry,
  type MailLogFilter,
  type MailLogListResponse,
  type MailSenderIdentity,
  type MailStatus,
  type Notification,
  type NotificationCreate,
  type NotificationListResponse,
  type NotificationRecipient,
  type NotificationTemplate,
  type NotificationTrigger,
  type NotificationTriggerInput,
  type NotificationUpdate,
  type Placeholder,
  type PlaceholderMatch,
  type SystemPlaceholder,
} from './mail.ts';
// Escaping and line breaking — **one** place, since the HTML export needs
// the same function as the notification. They stand here completely together,
// so that nobody finds `escapeHtml`, misses the line break and writes it
// beside it; that is the mistake.
export {
  SINGLE_LINE_TEXT,
  SINGLE_LINE_TEXT_MESSAGE,
  collapseWhitespace,
  escapeHtml,
  isSingleLineText,
  neutraliseHtml,
  stripMarkup,
} from './html-text.ts';
export {
  DEFERRED_EDIT_LINK,
  EDIT_LINK_MARK,
  EDIT_LINK_REDACTED_LABEL,
  NO_EDIT_LINK,
  PASSWORD_RESET_LINK_MARK,
  PASSWORD_RESET_LINK_REDACTED_LABEL,
  insertEditLink,
  insertPasswordResetLink,
  mailAnswerRowSchema,
  mailChangeRowSchema,
  mailTemplateContextSchema,
  parseRecipientList,
  renderAnswerTable,
  renderChangeTable,
  renderEditLink,
  renderMailSubject,
  renderMailTemplate,
  resolveRecipients,
  sanitizeSubject,
  truncateSubject,
  unknownPlaceholders,
  wrapMailBody,
  type EditLinkPresentation,
  type EditLinkSlot,
  type MailBodyPair,
  type MailShell,
  type MailShellLink,
  type MailShellLinkOwner,
  type PasswordResetLinkSlot,
  type MailAnswerRow,
  type MailLabelledValue,
  type MailChangeRow,
  type MailTemplateContext,
  type RecipientList,
  type RenderMailTemplateInput,
} from './mail-template.ts';
export {
  NOTIFICATION_TEMPLATES_FLOOR,
  NOTIFICATION_TEMPLATE_LIMIT,
  acceptsTemplate,
  notificationTemplatesDocumentSchema,
  parseNotificationTemplatesDocument,
  tenantNotificationTemplatesResponseSchema,
  updateTenantNotificationTemplatesRequestSchema,
  type TenantNotificationTemplatesResponse,
  type UpdateTenantNotificationTemplatesRequest,
} from './notification-templates.ts';
export {
  ADDRESS_QUESTION_TYPES,
  addressQuestionsOf,
  isAddressQuestion,
} from './address-questions.ts';
export {
  toDisplayForm,
  toStorageForm,
  unresolvedQuestionCaptions,
} from './mail-placeholder-display.ts';
export {
  DEADLINE_TIME_ZONE,
  berlinMonthStart,
  formatDeadline,
  toInstant,
  toLocalInput,
  zoneAbbreviation,
} from './berlin-time.ts';
export {
  parseInline,
  parseLegalText,
  safeLegalHref,
  stripControlChars,
  type LegalBlock,
  type LegalInline,
} from './legal-text.ts';
export {
  EMPTY_LEGAL_DOCUMENT,
  EMPTY_SYSTEM_LEGAL_PAGES,
  EMPTY_TENANT_LEGAL_PAGES,
  LEGAL_FILL_MAX,
  LEGAL_LINK_MAX,
  LEGAL_ORG_SEGMENT,
  LEGAL_TEXT_MAX,
  LICENCES_PATH,
  SYSTEM_LEGAL_PAGES,
  TENANT_LEGAL_PAGES,
  groupedSlots,
  isAppSlot,
  legalBlockSchema,
  legalDocumentSchema,
  legalDocumentWriteSchema,
  legalPageStatus,
  legalPageStatusSchema,
  openTenantLegalPages,
  parseStoredFormPrivacyNotice,
  parseStoredSystemLegalPages,
  parseStoredTenantLegalPages,
  publicFormPrivacyNoticeSchema,
  publicLegalFooterSchema,
  publicLegalPageSchema,
  renderFormPrivacyNotice,
  renderLegalPage,
  editableConditions,
  systemLegalPageOf,
  systemLegalPageSchema,
  systemLegalPagesSchema,
  systemLegalPath,
  templateDefects,
  visibleSlots,
  tenantLegalPageOf,
  tenantLegalPageSchema,
  tenantLegalPagesSchema,
  tenantLegalPath,
  tenantLegalStatus,
  updateSystemLegalRequestSchema,
  updateTenantLegalRequestSchema,
  type LegalAudience,
  type LegalCondition,
  type LegalDocument,
  type LegalPageStatus,
  type LegalRenderContext,
  type LegalSlot,
  type LegalSlotGroup,
  type LegalTemplate,
  type PublicFormPrivacyNotice,
  type PublicLegalFooter,
  type PublicLegalPage,
  type RenderedLegalPage,
  type SystemLegalPage,
  type SystemLegalPages,
  type TenantLegalPage,
  type TenantLegalPages,
  type UpdateSystemLegalRequest,
  type UpdateTenantLegalRequest,
} from './legal.ts';
export {
  FORM_PRIVACY_TEMPLATE,
  OPERATOR_NAME_SLOT,
  SYSTEM_LEGAL_TEMPLATES,
  TENANT_LEGAL_TEMPLATES,
} from './legal-templates.ts';
export { applySharedFills, sharedSlotKeys } from './legal-shared-fills.ts';
